server:
  port: 8080
spring:
  application:
    name: evaluation-zuul-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  prefix: /service
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000
    max-total-connections: 500
  routes:
    student:
      path: /student/**
      serviceId: evaluation-student-service
      strip-prefix: false
    teacher:
      path: /teacher/**
      serviceId: evaluation-teacher-service
      strip-prefix: false
    course:
      path: /course/**
      serviceId: evaluation-course-service
      strip-prefix: false
    data:
      path: /data/**
      serviceId: evaluation-data-service
      strip-prefix: false
    auth:
      path: /auth/**
      serviceId: evaluation-authorization-service
      strip-prefix: false
    studentAssessment:
      path: /evaluation/**
      serviceId: evaluation-studentevaluation-service
      strip-prefix: false
    thirdkpi:
      path: /thirdkpi/**
      serviceId: evaluation-thirdkpi-service
      strip-prefix: false
# 加密密钥
auth:
  secret: 9O2B+amfn52nzowCysmC7+hfuA0q9xvxcgLU1UDVYwM=