server:
  port: 7002
  servlet:
    context-path: /auth
spring:
  application:
    name: evaluation-authorization-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/right
    #  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/xynu_evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
#mybatis:
#  config-location: classpath:myBatisConfig.xml

#enable配置为false时在运行时生成密钥, 停止应用后密钥丢失。所有签发的token将失效
#为true时使用secret的密钥签发token 停止应用后签发的token不会失效
auth:
  enable: true
  secret: 9O2B+amfn52nzowCysmC7+hfuA0q9xvxcgLU1UDVYwM=