server:
  port: 7013
  servlet:
    context-path: /thirdkpi
spring:
  application:
    name: evaluation-thirdkpi-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xynu_evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
mybatis:
  config-location: classpath:myBatisConfig.xml