spring:
  application:
    name: evaluation-analysis-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      connection-timeout: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: evaluation
    password: 123456
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/evaluation
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
server:
  port: 7030
  servlet:
    context-path: /analysis
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true