server:
  port: 7009
  servlet:
    context-path: /sevaluation
spring:
  application:
    name: evaluation-studentevaluation-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/evaluation
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: student_evaluation
    password: 123456
    connection-timeout: 15000
    publisher-returns: true
    publisher-confirm-type: correlated
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true