server:
  port: 7052
  servlet:
    context-path: /teacherevaluation
spring:
  application:
    name: evaluation-teacher-evaluation
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/teacherevaluation
eureka:
  client:
    service-url:
      defaultZone: http://tusdasa:8000/eureka/
feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true