server:
  port: 8084
spring:
  application:
    name: evaluation-operations
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
  mail:
    host: 127.0.0.1
    default-encoding: UTF-8
    prot: 22
    protocol: smtp
    username: tusdasa@local.net
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
  boot:
    admin:
      notify:
        mail:
          to: test@local.net
          from: tusdasa@local.net
